services:
  mariadb:
    image: 'mariadb:12.0'
    environment:
      - 'MARIADB_DATABASE=aws-controller'
      - 'MARIADB_PASSWORD=aws-secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=aws_hanif'
    ports:
      - '3306'
